#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python app/load_fixtures.py
ray start --head --dashboard-host 0.0.0.0 --dashboard-port $RAY_DASHBOARD_PORT 
serve run app.main:deployment --host 0.0.0.0 --port $APP_PORT