version: '3.8'

services:

  mongo:
    image: mongo:6.0.2
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    env_file:
    - ./.env

volumes:
  mongo_data: