version: '3.8'

services:
  app:
    build: ./app
    command: /start
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongo
    
  mongo:
    image: mongo:6.0.2
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./.env

volumes:
  mongo_data: